### ISSUE TITLE
'aiida_optimize.engines._result_mapping' is not imported exception

### ISSUE THREAD

**Issue by unkcpz** [greschd/aiida-optimize#29]
Hi @zooks97 , I got the following exception when I running the convergence test. Do you have any idea how this happened? 
I just paste part of the traceback, ask me for more information if it is needed.

```
....
  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 593, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 566, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 593, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 566, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'aiida_optimize.engines._result_mapping' is not imported
  in "<unicode string>", line 49, column 10:
          0: !!python/object:aiida_optimize.e ...
  File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'aiida_optimize.engines._result_mapping' is not imported
  in "<unicode string>", line 49, column 10:
          0: !!python/object:aiida_optimize.e ...
```

Here is the example file I changed a little on top of your demo https://gist.github.com/unkcpz/87d8564560ecb8066b390dea09ef80d5

**Comment by greschd** [comment]
Seems related to https://github.com/aiidateam/aiida-core/issues/3709, although I don't quite understand why this showed up here (and not in our tests).

In [this branch](https://github.com/greschd/aiida-optimize/tree/import_everything) I changed the `__init__.py`'s to import all submodules directly - can you check whether that might work as a work-around?

As it may be relevant: which version of `pyyaml` is installed in your system?

**Comment by unkcpz** [comment]
Hi @greschd the `import_everything` branch still not working and raise the same exception once I restart the daemon :pensive: 
the version of yaml is: 
```
aspy.yaml==1.3.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
```
didn't have `pyyaml` installed.

**Comment by greschd** [comment]
>  still not working and raise the same exception once I restart the daemon 😔

Well, that was a bit of a long shot, didn't really expect that to work.

Hm, there should be a version of `pyyaml` installed, from this requirement: https://github.com/aiidateam/aiida-core/blob/develop/setup.json#L48. Maybe you need to grep with `-i`, because it's listed as `PyYAML`.

**Comment by greschd** [comment]
To confirm this is is related to https://github.com/aiidateam/aiida-core/issues/3709, you could apply the following patch to `aiida-core` and check if the problem is still present.

Note that this is unsafe in the following sense: If you import an AiiDA archive from an untrusted source that contains maliciously crafted "checkpoints", it can execute arbitrary code. The proposed solution in https://github.com/aiidateam/aiida-core/issues/3709 is to remove all checkpoints when importing.
If you never load untrusted archives however, the patch below is sufficient.

```patch
diff --git a/aiida/orm/utils/serialize.py b/aiida/orm/utils/serialize.py
index 23aa68348..70fc09070 100644
--- a/aiida/orm/utils/serialize.py
+++ b/aiida/orm/utils/serialize.py
@@ -176,7 +176,7 @@ class AiiDADumper(yaml.Dumper):
         return super().represent_data(data)


-class AiiDALoader(yaml.FullLoader):
+class AiiDALoader(yaml.UnsafeLoader):
     """AiiDA specific yaml loader

     .. note:: we subclass the `FullLoader` which is the one that since `pyyaml>=5.1` is the loader that prevents
```

**Comment by unkcpz** [comment]
@greschd , my `pyyaml` version is 5.1.2. For the time being, I'll use the workaround, thanks!
