### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by unkcpz** [greschd/aiida-optimize#30]
hi @greschd, I use some features added by @zooks97. But it is now in the `develop` branch. Do you have any plan to release next  version? So I do not need to use git install in my ci setting.

**Comment by greschd** [comment]
Yeah no problem, I can make a release. Initially I wanted to wait for some other changes we had been talking about, but it'll probably take a while to get around to that and there's no downside to releasing what's now in `develop`.

**Comment by unkcpz** [comment]
much appreciate!On Thu, Dec 17, 2020 at 17:53 Dominik Gresch <notifications@github.com> wrote:
Closed #30 via #31.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by greschd** [comment]
https://pypi.org/project/aiida-optimize/0.4.0/
