### ISSUE TITLE
handle the failed evaluate process of OptimizationWorkChain

### ISSUE THREAD

**Issue by unkcpz** [greschd/aiida-optimize#34]
Currently, if one of the evaluate process failed in `OptimizationWorkChain`, the workflow will stop with exit_code `201`. There are lots of scenarios that some failed processes are allowed. So a way to elegantly handle the failed process is needed. 

Tagging @greschd @zooks97 for inputs.

**Comment by greschd** [comment]
We've started discussing this in #22. @unkcpz it would be great if you could comment on the options discussed there, and / or add some context from your use case for how you would like to react to the evaluate process failure.

**Comment by unkcpz** [comment]
Ha, yes didn't notice that issue. My bad.
