### ISSUE TITLE
`max_iter` argument of `NelderMead` engine is ignored

### ISSUE THREAD

**Issue by bosonie** [greschd/aiida-optimize#41]
The `max_iter` argument of `NelderMead` does not seem to have any effect.
Also, a quick look at the code seems to suggest that the attribute `self.max_iter` is set but never used.

**Comment by greschd** [comment]
Good catch, the number of iterations is kept track of in `num_iter`, but the check for aborting is missing.

**Comment by bosonie** [comment]
Just a further comment, `num_iter` keeps track of the iterations of the algorithm, but in each iteration there are several "evaluations". Only the start and finish of a new "evaluation" is reported in the log. Therefore a user might be confused by the fact that `max_iter` is set to N, but the logs shows many more "evaluations". I would suggest to add a report counting the iterations.
I can make a PR fixing the bug and adding this if you wish @greschd.

**Comment by greschd** [comment]
>  I can make a PR fixing the bug and adding this if you wish @greschd.

Would be very much appreciated!

I think the engine should set the `is_finished_ok` property to `False` in this case 

https://github.com/greschd/aiida-optimize/blob/61dbab634c1fd74804813703252f630791b2872c/aiida_optimize/engines/base.py#L66

which will cause the 202 exit code to be emitted:

https://github.com/greschd/aiida-optimize/blob/61dbab634c1fd74804813703252f630791b2872c/aiida_optimize/_optimization_workchain.py#L57-L61
