### ISSUE TITLE
development status now parsed from `setup.json`

### ISSUE THREAD

**Issue by ltalirz** [greschd/aiida-optimize#45]
In order to remove duplication, we're removing the development status from the aiida plugin registry   and parsing it from the `setup.json` instead.

Just mentioning that on the code registry, the plugin was listed as "stable", while the `setup.json` currently indicates "beta" in `master` (not in `develop`).
https://github.com/greschd/aiida-optimize/blob/2155319beae37a05339608f21d8c32af3e459776/setup.json#L11

Feel free to close this issue if you're fine with the "beta" status - otherwise please update the `setup.json` of the `master` branch.

**Comment by greschd** [comment]
Yeah, it's fine to parse from `setup.json`. 

I think initially there was some guidance that (paraphrasing) "if you can use it in production, but want to change the API later on it can be "stable" on the registry with a "Beta" classifier" -- but I can neither find that discussion, nor is it necessarily such a useful distinction.

Of course, now changing the classifier potentially needs a release -- but the chance of it being up-to-date is anyway better when the status is only in one place.
